using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace APIPaises
{
    public class FormatoJson
    {

        public class Paises
        {
            public string BD { get; set; }
            public string BE { get; set; }
            public string BF { get; set; }
            public string BG { get; set; }
            public string BA { get; set; }
            public string BB { get; set; }
            public string WF { get; set; }
            public string BL { get; set; }
            public string BM { get; set; }
            public string BN { get; set; }
            public string BO { get; set; }
            public string BH { get; set; }
            public string BI { get; set; }
            public string BJ { get; set; }
            public string BT { get; set; }
            public string JM { get; set; }
            public string BV { get; set; }
            public string BW { get; set; }
            public string WS { get; set; }
            public string BQ { get; set; }
            public string BR { get; set; }
            public string BS { get; set; }
            public string JE { get; set; }
            public string BY { get; set; }
            public string BZ { get; set; }
            public string RU { get; set; }
            public string RW { get; set; }
            public string RS { get; set; }
            public string TL { get; set; }
            public string RE { get; set; }
            public string TM { get; set; }
            public string TJ { get; set; }
            public string RO { get; set; }
            public string TK { get; set; }
            public string GW { get; set; }
            public string GU { get; set; }
            public string GT { get; set; }
            public string GS { get; set; }
            public string GR { get; set; }
            public string GQ { get; set; }
            public string GP { get; set; }
            public string JP { get; set; }
            public string GY { get; set; }
            public string GG { get; set; }
            public string GF { get; set; }
            public string GE { get; set; }
            public string GD { get; set; }
            public string GB { get; set; }
            public string GA { get; set; }
            public string SV { get; set; }
            public string GN { get; set; }
            public string GM { get; set; }
            public string GL { get; set; }
            public string GI { get; set; }
            public string GH { get; set; }
            public string OM { get; set; }
            public string TN { get; set; }
            public string JO { get; set; }
            public string HR { get; set; }
            public string HT { get; set; }
            public string HU { get; set; }
            public string HK { get; set; }
            public string HN { get; set; }
            public string HM { get; set; }
            public string VE { get; set; }
            public string PR { get; set; }
            public string PS { get; set; }
            public string PW { get; set; }
            public string PT { get; set; }
            public string SJ { get; set; }
            public string PY { get; set; }
            public string IQ { get; set; }
            public string PA { get; set; }
            public string PF { get; set; }
            public string PG { get; set; }
            public string PE { get; set; }
            public string PK { get; set; }
            public string PH { get; set; }
            public string PN { get; set; }
            public string PL { get; set; }
            public string PM { get; set; }
            public string ZM { get; set; }
            public string EH { get; set; }
            public string EE { get; set; }
            public string EG { get; set; }
            public string ZA { get; set; }
            public string EC { get; set; }
            public string IT { get; set; }
            public string VN { get; set; }
            public string SB { get; set; }
            public string ET { get; set; }
            public string SO { get; set; }
            public string ZW { get; set; }
            public string SA { get; set; }
            public string ES { get; set; }
            public string ER { get; set; }
            public string ME { get; set; }
            public string MD { get; set; }
            public string MG { get; set; }
            public string MF { get; set; }
            public string MA { get; set; }
            public string MC { get; set; }
            public string UZ { get; set; }
            public string MM { get; set; }
            public string ML { get; set; }
            public string MO { get; set; }
            public string MN { get; set; }
            public string MH { get; set; }
            public string MK { get; set; }
            public string MU { get; set; }
            public string MT { get; set; }
            public string MW { get; set; }
            public string MV { get; set; }
            public string MQ { get; set; }
            public string MP { get; set; }
            public string MS { get; set; }
            public string MR { get; set; }
            public string IM { get; set; }
            public string UG { get; set; }
            public string TZ { get; set; }
            public string MY { get; set; }
            public string MX { get; set; }
            public string IL { get; set; }
            public string FR { get; set; }
            public string IO { get; set; }
            public string SH { get; set; }
            public string FI { get; set; }
            public string FJ { get; set; }
            public string FK { get; set; }
            public string FM { get; set; }
            public string FO { get; set; }
            public string NI { get; set; }
            public string NL { get; set; }
            public string NO { get; set; }
            public string NA { get; set; }
            public string VU { get; set; }
            public string NC { get; set; }
            public string NE { get; set; }
            public string NF { get; set; }
            public string NG { get; set; }
            public string NZ { get; set; }
            public string NP { get; set; }
            public string NR { get; set; }
            public string NU { get; set; }
            public string CK { get; set; }
            public string XK { get; set; }
            public string CI { get; set; }
            public string CH { get; set; }
            public string CO { get; set; }
            public string CN { get; set; }
            public string CM { get; set; }
            public string CL { get; set; }
            public string CC { get; set; }
            public string CA { get; set; }
            public string CG { get; set; }
            public string CF { get; set; }
            public string CD { get; set; }
            public string CZ { get; set; }
            public string CY { get; set; }
            public string CX { get; set; }
            public string CR { get; set; }
            public string CW { get; set; }
            public string CV { get; set; }
            public string CU { get; set; }
            public string SZ { get; set; }
            public string SY { get; set; }
            public string SX { get; set; }
            public string KG { get; set; }
            public string KE { get; set; }
            public string SS { get; set; }
            public string SR { get; set; }
            public string KI { get; set; }
            public string KH { get; set; }
            public string KN { get; set; }
            public string KM { get; set; }
            public string ST { get; set; }
            public string SK { get; set; }
            public string KR { get; set; }
            public string SI { get; set; }
            public string KP { get; set; }
            public string KW { get; set; }
            public string SN { get; set; }
            public string SM { get; set; }
            public string SL { get; set; }
            public string SC { get; set; }
            public string KZ { get; set; }
            public string KY { get; set; }
            public string SG { get; set; }
            public string SE { get; set; }
            public string SD { get; set; }
            public string DO { get; set; }
            public string DM { get; set; }
            public string DJ { get; set; }
            public string DK { get; set; }
            public string VG { get; set; }
            public string DE { get; set; }
            public string YE { get; set; }
            public string DZ { get; set; }
            public string US { get; set; }
            public string UY { get; set; }
            public string YT { get; set; }
            public string UM { get; set; }
            public string LB { get; set; }
            public string LC { get; set; }
            public string LA { get; set; }
            public string TV { get; set; }
            public string TW { get; set; }
            public string TT { get; set; }
            public string TR { get; set; }
            public string LK { get; set; }
            public string LI { get; set; }
            public string LV { get; set; }
            public string TO { get; set; }
            public string LT { get; set; }
            public string LU { get; set; }
            public string LR { get; set; }
            public string LS { get; set; }
            public string TH { get; set; }
            public string TF { get; set; }
            public string TG { get; set; }
            public string TD { get; set; }
            public string TC { get; set; }
            public string LY { get; set; }
            public string VA { get; set; }
            public string VC { get; set; }
            public string AE { get; set; }
            public string AD { get; set; }
            public string AG { get; set; }
            public string AF { get; set; }
            public string AI { get; set; }
            public string VI { get; set; }
            public string IS { get; set; }
            public string IR { get; set; }
            public string AM { get; set; }
            public string AL { get; set; }
            public string AO { get; set; }
            public string AQ { get; set; }
            public string AS { get; set; }
            public string AR { get; set; }
            public string AU { get; set; }
            public string AT { get; set; }
            public string AW { get; set; }
            public string IN { get; set; }
            public string AX { get; set; }
            public string AZ { get; set; }
            public string IE { get; set; }
            public string ID { get; set; }
            public string UA { get; set; }
            public string QA { get; set; }
            public string MZ { get; set; }
        }

    }
}
